#!/usr/bin/env python3
"""Safe setup and two-stage flash orchestration for CANVAS Klipper."""
from __future__ import annotations

import argparse
import datetime as dt
import glob
import hashlib
import importlib.machinery
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
FLASH_SCRIPT = ROOT / "flash/canvas-flash"
KATAPULT_VID_PID = "1d50:6177"
KLIPPER_VID_PID = "1d50:614e"
FLASH_RUNNER = subprocess.run
COSMOS_VENDOR = "ShenZhenCBD"  # Observed in COSMOS init script; unverified hardware identity.
COSMOS_BY_PATH_HINT = "platform-4200000.usb-usb-0:1.4:1.0"  # COSMOS host-specific, not a portable selector.
INCLUDE_LINE = "[include canvas/*.cfg]"
MANAGED_HEADER = "# Generated by canvas-klipper installer; review measured pins before use."


def load_flasher():
    loader = importlib.machinery.SourceFileLoader("canvas_flash", str(FLASH_SCRIPT))
    spec = importlib.util.spec_from_loader(loader.name, loader)
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


flash_tool = load_flasher()
FLASH_IDENTITY_READER = flash_tool.linux_usb_ids


def ask(prompt: str, *, non_interactive: bool = False, value: str | None = None) -> str:
    if value is not None:
        return value
    if non_interactive:
        raise ValueError("non-interactive mode requires a value for: " + prompt.rstrip(": "))
    return input(prompt).strip()


def backup_path(path: Path) -> Path:
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S.%fZ")
    candidate = path.with_name(path.name + "." + stamp + ".bak")
    counter = 1
    while candidate.exists() or candidate.is_symlink():
        candidate = path.with_name(path.name + "." + stamp + "." + str(counter) + ".bak")
        counter += 1
    if path.is_symlink():
        # Preserve the link itself, including its target, without dereferencing it.
        os.symlink(os.readlink(path), candidate)
    elif path.is_dir():
        shutil.copytree(path, candidate, symlinks=True)
    else:
        with path.open("rb") as source, candidate.open("xb") as destination:
            shutil.copyfileobj(source, destination)
        shutil.copystat(path, candidate, follow_symlinks=False)
    return candidate


def move_to_backup(path: Path) -> Path:
    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%S.%fZ")
    candidate = path.with_name(path.name + "." + stamp + ".bak")
    counter = 1
    while candidate.exists() or candidate.is_symlink():
        candidate = path.with_name(path.name + "." + stamp + "." + str(counter) + ".bak")
        counter += 1
    os.rename(path, candidate)
    return candidate


def rewrite_preserving(path: Path, content: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else ""
    if old == content:
        return False
    if path.exists():
        saved = backup_path(path)
        print("Backup: " + str(saved))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def query_print_state(url: str, timeout: float = 3.0) -> str:
    parsed = urllib.parse.urlsplit(url)
    if (parsed.scheme not in ("http", "https") or not parsed.hostname or parsed.username or
            parsed.password or parsed.query or parsed.fragment):
        raise ValueError("Moonraker URL must be an HTTP(S) base URL without credentials or query data")
    base = url.rstrip("/")
    endpoint = base + "/printer/objects/query?print_stats"
    request = urllib.request.Request(endpoint, headers={"Accept": "application/json"})
    with urllib.request.urlopen(request, timeout=timeout) as response:
        data = json.loads(response.read().decode("utf-8"))
    state = data.get("result", {}).get("status", {}).get("print_stats", {}).get("state")
    return state.lower() if isinstance(state, str) else "unknown"


def require_idle(url: str, force: bool = False) -> str:
    try:
        state = query_print_state(url)
    except (OSError, ValueError, urllib.error.URLError, json.JSONDecodeError):
        state = "unknown"
    if state in ("printing", "paused"):
        raise ValueError("Moonraker reports %s; refusing to proceed" % state)
    if state == "unknown" and not force:
        raise ValueError("Moonraker print state is unknown; use --force only if independently verified idle")
    return state


def section_names(path: Path) -> list[str]:
    return [m.group(1).strip() for m in re.finditer(r"(?m)^\s*\[([^]\n]+)\]\s*(?:#.*)?$", path.read_text(encoding="utf-8"))]


def included_files(printer_cfg: Path) -> list[Path]:
    root = printer_cfg.parent
    pending = [printer_cfg.resolve()]
    visited: set[Path] = set()
    result: list[Path] = []
    include_re = re.compile(r"(?im)^\s*\[include\s+([^]\n]+)\]\s*(?:#.*)?$")
    while pending:
        current = pending.pop()
        if current in visited or not current.is_file():
            continue
        visited.add(current)
        result.append(current)
        text = current.read_text(encoding="utf-8")
        for match in include_re.finditer(text):
            expression = match.group(1).strip()
            pattern = Path(expression)
            if not pattern.is_absolute():
                pattern = root / pattern
            for item in glob.glob(str(pattern), recursive=True):
                target = Path(item).resolve()
                if target.is_file() and target not in visited:
                    pending.append(target)
    return result


def detect_config(printer_cfg: Path) -> tuple[list[str], list[str]]:
    names: list[str] = []
    sensors: list[str] = []
    for file in included_files(printer_cfg):
        for section in section_names(file):
            if section.lower() == "extruder":
                names.append(section)
            match = re.fullmatch(r"filament_switch_sensor\s+(.+)", section, re.I)
            if match:
                sensors.append(match.group(1).strip())
    return names, sorted(set(sensors), key=str.lower)


def normalize_include(text: str) -> str:
    return "\n".join(line for line in text.splitlines()
                     if line.strip().lower() != INCLUDE_LINE.lower())


def canvas_settings(printer_cfg: Path) -> dict[str, dict[str, str]]:
    settings: dict[str, dict[str, str]] = {}
    current = None
    seen_sections: set[str] = set()
    duplicate_sections = False
    for path in included_files(printer_cfg):
        for line in path.read_text(encoding="utf-8").splitlines():
            header = re.fullmatch(r"\s*\[([^]\n]+)\]\s*(?:#.*)?", line)
            if header:
                current = header.group(1).strip().casefold()
                if current in seen_sections:
                    duplicate_sections = True
                seen_sections.add(current)
                settings.setdefault(current, {})
                continue
            if current is None or not line.strip() or line.lstrip().startswith("#"):
                continue
            option = re.match(r"\s*([A-Za-z0-9_.-]+)\s*[:=]\s*(.*?)\s*(?:#.*)?$", line)
            if option:
                settings[current][option.group(1).casefold()] = option.group(2).strip()
    if duplicate_sections:
        settings["__duplicate_sections__"] = {}
    return settings


def canvas_config_complete(printer_cfg: Path) -> bool:
    settings = canvas_settings(printer_cfg)
    if "__duplicate_sections__" in settings:
        return False
    canvas = settings.get("canvas", {})
    serial = settings.get("mcu canvas", {}).get("serial", "")
    sensor = canvas.get("toolhead_sensor", "")
    if not serial or not sensor or "TO_BE_MEASURED" in serial.upper():
        return False
    sensor_pin = settings.get(("filament_switch_sensor " + sensor).casefold(), {}).get("switch_pin", "")
    if not sensor_pin or "TO_BE_MEASURED" in sensor_pin.upper():
        return False
    for lane in range(4):
        key = "lane_t%d_" % lane
        motor = canvas.get(key + "motor", "")
        lane_values = (motor, canvas.get(key + "present_pin", ""), canvas.get(key + "prep_pin", ""))
        if any(not value or "TO_BE_MEASURED" in value.upper() for value in lane_values):
            return False
        driver = settings.get(("drv8833 " + motor).casefold(), {})
        if any(not driver.get(option) or "TO_BE_MEASURED" in driver.get(option, "").upper()
               for option in ("motor_fwd", "motor_rwd", "motor_hall", "motor_hall_resolution")):
            return False
    return True


def update_option(text: str, section: str, key: str, value: str) -> str:
    header = re.compile(r"(?m)^\s*\[" + re.escape(section) + r"\]\s*(?:#.*)?$")
    match = header.search(text)
    if not match:
        raise ValueError("generated Canvas config is missing [%s]" % section)
    next_header = re.compile(r"(?m)^\s*\[[^]\n]+\]")
    following = next_header.search(text, match.end())
    end = following.start() if following else len(text)
    block = text[match.start():end]
    option = re.compile(r"(?m)^(\s*" + re.escape(key) + r"\s*[:=]\s*).*$", re.I)
    if option.search(block):
        block = option.sub(lambda m: m.group(1) + value, block, count=1)
    else:
        position = block.find("\n") + 1
        block = block[:position] + key + ": " + value + "\n" + block[position:]
    return text[:match.start()] + block + text[end:]


def make_canvas_config(sensor: str, method: str, serial: str, add_sensor_pin: str | None) -> str:
    template = (ROOT / "config/canvas.cfg").read_text(encoding="utf-8")
    template = re.sub(r"(?ms)^\[filament_switch_sensor\s+[^]\n]+\]\n.*?(?=^\[|\Z)", "", template)
    template = re.sub(r"(?im)^\s*\[include\s+canvas_macros\.cfg\]\s*\n", "", template)
    template = re.sub(r"(?m)^toolhead_sensor\s*:\s*.*$", "toolhead_sensor: " + sensor, template)
    template = re.sub(r"(?m)^separation_method\s*:\s*.*$", "separation_method: " + method, template)
    mcu = "[mcu canvas]\nserial: " + serial + "\n\n"
    if add_sensor_pin:
        mcu += "[filament_switch_sensor %s]\nswitch_pin: %s\npause_on_runout: False\n\n" % (sensor, add_sensor_pin)
    return MANAGED_HEADER + "\n" + mcu + template.lstrip()


def copy_templates(config_dir: Path, sensor: str, method: str, serial: str,
                   new_sensor_pin: str | None) -> bool:
    canvas_dir = config_dir / "canvas"
    canvas_dir.mkdir(parents=True, exist_ok=True)
    generated = {
        "canvas.cfg": make_canvas_config(sensor, method, serial, new_sensor_pin),
        "canvas_macros.cfg": (ROOT / "config/canvas_macros.cfg").read_text(encoding="utf-8"),
        "slicer-snippets.cfg.example": (ROOT / "config/slicer-snippets.cfg").read_text(encoding="utf-8"),
    }
    changed = False
    for name, content in generated.items():
        path = canvas_dir / name
        if path.exists():
            if not path.is_file():
                raise ValueError("Refusing to replace non-file user path: " + str(path))
            if name != "canvas.cfg":
                continue  # These copied templates may now contain user edits; never overwrite them.
            current = path.read_text(encoding="utf-8")
            if not current.startswith(MANAGED_HEADER):
                raise ValueError("Refusing to overwrite unmarked user file: " + str(path))
            content = current
            for section, key, value in (("mcu canvas", "serial", serial),
                                        ("canvas", "toolhead_sensor", sensor),
                                        ("canvas", "separation_method", method)):
                content = update_option(content, section, key, value)
            changed |= rewrite_preserving(path, content)
        else:
            with path.open("x", encoding="utf-8") as destination:
                destination.write(content)
            changed = True
    return changed


def config_digest(config_dir: Path, printer_cfg: Path, moonraker_cfg: Path) -> str:
    digest = hashlib.sha256()
    paths = [printer_cfg, moonraker_cfg, *sorted((config_dir / "canvas").glob("*.cfg"))]
    for path in paths:
        digest.update(str(path.name).encode("utf-8") + b"\0")
        digest.update(path.read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()


def update_manager_section(repo: Path) -> str:
    return ("[update_manager canvas-klipper]\n"
            "type: git_repo\n"
            "path: %s\n"
            "origin: git@github.com:yazdannl/canvas-klipper.git\n"
            "primary_branch: main\n"
            "managed_services: klipper\n" % repo)


def section_block(text: str, name: str) -> str | None:
    pattern = re.compile(r"(?ms)^\[" + re.escape(name) + r"\]\s*\n.*?(?=^\[|\Z)", re.I)
    match = pattern.search(text)
    return match.group(0).strip() if match else None


def serial_paths() -> list[Path]:
    by_id = Path(os.environ.get("CANVAS_SERIAL_BY_ID_DIR", "/dev/serial/by-id"))
    dev_root = Path(os.environ.get("CANVAS_DEV_DIR", "/dev"))
    found: dict[str, Path] = {}
    if by_id.is_dir():
        for p in sorted(by_id.iterdir()):
            if p.is_char_device() or p.is_symlink():
                found[os.path.realpath(p)] = p
    by_path = Path(os.environ.get("CANVAS_SERIAL_BY_PATH_DIR", "/dev/serial/by-path"))
    if by_path.is_dir():
        for p in sorted(by_path.iterdir()):
            if p.is_char_device() or p.is_symlink():
                found.setdefault(os.path.realpath(p), p)
    for pattern in ("ttyACM*", "ttyUSB*"):
        for p in sorted(dev_root.glob(pattern)):
            if p.is_char_device() or p.is_symlink():
                found.setdefault(os.path.realpath(p), p)
    return list(found.values())


def device_info(device: Path) -> dict[str, str | None]:
    # Test-only roots allow simulated sysfs identities; normal operation reads sysfs/udev.
    root = Path(os.environ.get("CANVAS_SYSFS_ROOT", "/sys/class/tty"))
    tty = Path(os.path.realpath(device)).name
    node = root / tty / "device"
    try:
        resolved = node.resolve(strict=True)
        for parent in (resolved, *resolved.parents):
            vendor = parent / "idVendor"
            product = parent / "idProduct"
            if vendor.is_file() and product.is_file():
                vid = vendor.read_text(encoding="ascii").strip().lower()
                pid = product.read_text(encoding="ascii").strip().lower()
                return {"vid_pid": vid + ":" + pid,
                        "vendor": read_optional(parent / "manufacturer"),
                        "product": read_optional(parent / "product")}
    except OSError:
        pass
    try:
        result = subprocess.run(["udevadm", "info", "--query=property", "--name", str(device)],
                                check=True, text=True, capture_output=True)
        props = dict(line.split("=", 1) for line in result.stdout.splitlines() if "=" in line)
        vid = props.get("ID_VENDOR_ID")
        pid = props.get("ID_MODEL_ID")
        return {"vid_pid": (vid + ":" + pid).lower() if vid and pid else None,
                "vendor": props.get("ID_VENDOR"), "product": props.get("ID_MODEL")}
    except (OSError, subprocess.SubprocessError):
        return {"vid_pid": None, "vendor": None, "product": None}


def display_label(value: str | None) -> str:
    return re.sub(r"[\x00-\x1f\x7f]+", " ", value or "unknown").strip()[:80] or "unknown"


def read_optional(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8").strip()
    except OSError:
        return None


def detect_device(device: str | None, vid_pid: str | None, *, prompt: bool = True,
                  input_fn=input, output=print) -> tuple[str, str]:
    if device:
        path = Path(device)
        if not path.exists():
            raise ValueError("device does not exist: " + device)
        info = device_info(path)
        actual = info["vid_pid"]
        if not actual:
            raise ValueError("cannot verify USB identity for --device; supply a readable USB serial device")
        if vid_pid and actual != vid_pid.lower():
            raise ValueError("USB identity mismatch: expected %s, found %s" % (vid_pid, actual))
        return str(path), actual

    if vid_pid:
        matches = [(p, device_info(p)) for p in serial_paths()]
        matches = [(p, i) for p, i in matches if i["vid_pid"] == vid_pid.lower()]
        if len(matches) != 1:
            raise ValueError("expected exactly one USB candidate matching %s, found %d" % (vid_pid, len(matches)))
        return str(matches[0][0]), str(matches[0][1]["vid_pid"])

    if not prompt:
        raise ValueError("auto-detection requires an interactive unplug/replug or --device/--vid-pid")
    output("Using COSMOS's unverified vendor filter %s (host by-path hint: %s)." %
           (COSMOS_VENDOR, COSMOS_BY_PATH_HINT))
    output("Unplug the Canvas USB cable now, then press Enter.")
    input_fn("")
    before = {os.path.realpath(p) for p in serial_paths()}
    output("Plug in the Canvas USB cable, wait for enumeration, then press Enter.")
    input_fn("")
    added = [p for p in serial_paths() if os.path.realpath(p) not in before]
    if len(added) != 1:
        raise ValueError("plug/unplug detection found %d new serial devices; expected exactly one" % len(added))
    info = device_info(added[0])
    if not info["vid_pid"]:
        raise ValueError("new serial device has no readable USB VID:PID")
    if (info["vendor"] or "").casefold() != COSMOS_VENDOR.casefold():
        raise ValueError("new device vendor did not match COSMOS's unverified %s filter; specify --device or --vid-pid" % COSMOS_VENDOR)
    output("Detected %s VID:PID %s, vendor %s (unverified filter from COSMOS), product %s" %
           (added[0], info["vid_pid"], info["vendor"] or "unknown", info["product"] or "unknown"))
    return str(added[0]), str(info["vid_pid"])


def wait_for_device(expected_vid_pid: str, timeout: float = 30.0,
                    paths=None, sleep=time.sleep) -> tuple[str, str]:
    paths = paths or serial_paths
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        matches = [(p, device_info(p)) for p in paths()]
        matches = [(p, i) for p, i in matches if i["vid_pid"] == expected_vid_pid.lower()]
        if len(matches) == 1:
            return str(matches[0][0]), str(matches[0][1]["vid_pid"])
        if len(matches) > 1:
            raise ValueError("multiple devices enumerated as %s" % expected_vid_pid)
        sleep(0.5)
    raise ValueError("device did not re-enumerate as %s within %.0fs" % (expected_vid_pid, timeout))


def flash(args) -> int:
    if not args.dry_run and args.yes and not args.i_understand_the_risks:
        raise ValueError("--yes requires --i-understand-the-risks")
    if not args.dry_run and args.non_interactive and not args.yes:
        raise ValueError("--non-interactive flash requires --yes --i-understand-the-risks")
    if args.dry_run:
        # Dry-run remains fully offline and does not inspect devices, Moonraker or run builders.
        outputs = (ROOT / "firmware/build-output/katapult-deployer-canvas.bin",
                   ROOT / "firmware/build-output/canvas-klipper.bin",
                   flash_tool.PINNED_MCU_FLASHER, flash_tool.PINNED_KATAPULT_FLASHTOOL)
        state = "firmware outputs are present; would rebuild if stale" if all(p.is_file() for p in outputs) else \
            "firmware outputs are missing; would run firmware/build.sh all"
        print("DRY RUN: %s, check Moonraker state, detect one Canvas USB device, then flash Katapult and Klipper." % state)
        print("Firmware target remains experimental (GD32F303 vs STM32F401); no stock backup is available; recovery may require SWD.")
        return 0

    require_idle(args.moonraker_url, args.force)
    outputs = [ROOT / "firmware/build-output/katapult-deployer-canvas.bin",
               ROOT / "firmware/build-output/canvas-klipper.bin",
               flash_tool.PINNED_MCU_FLASHER, flash_tool.PINNED_KATAPULT_FLASHTOOL]
    inputs = [ROOT / "firmware/build.sh", ROOT / "firmware/versions.lock",
              ROOT / "firmware/katapult/canvas.config", ROOT / "firmware/klipper/canvas.config",
              ROOT / "firmware/linux-process.config", ROOT / "klipper/0001-drv8833-mcu.patch",
              ROOT / "klipper/klippy/extras/drv8833.py"]
    stale = any(not p.is_file() or p.stat().st_size == 0 for p in outputs) or max(
        p.stat().st_mtime for p in inputs) > min(p.stat().st_mtime for p in outputs if p.is_file())
    if stale:
        if not shutil.which("make") or not shutil.which("git"):
            raise ValueError("firmware build dependencies are missing")
        if not all(shutil.which(x) for x in ("arm-none-eabi-gcc", "arm-none-eabi-objcopy", "cargo", "pkg-config")):
            apt_get = shutil.which("apt-get")
            privilege = [] if os.geteuid() == 0 else (["sudo"] if shutil.which("sudo") else None)
            if not apt_get or privilege is None:
                raise ValueError("firmware dependencies are missing and apt-get/privilege escalation are unavailable")
            if args.non_interactive and not args.yes:
                raise ValueError("non-interactive dependency installation requires --yes --i-understand-the-risks")
            if not args.yes and input("Install firmware build dependencies with apt? [y/N] ").strip().lower() != "y":
                raise ValueError("dependency installation declined")
            subprocess.run(privilege + [apt_get, "update"], check=True)
            subprocess.run(privilege + [apt_get, "install", "-y", "git", "make", "python3", "gcc-arm-none-eabi",
                            "binutils-arm-none-eabi", "libnewlib-dev", "libnewlib-arm-none-eabi",
                            "cargo", "pkg-config", "libudev-dev"], check=True)
        subprocess.run([str(ROOT / "firmware/build.sh"), "all"], check=True)

    first_device, first_vidpid = detect_device(args.device, args.vid_pid,
                                               prompt=not args.non_interactive)
    info = device_info(Path(first_device))
    if info["vid_pid"] and str(info["vid_pid"]).lower() != first_vidpid.lower():
        raise ValueError("USB identity changed after device selection")
    product = display_label(info["product"])
    vendor = display_label(info["vendor"])
    print("Flash target: %s VID:PID %s, vendor %s, product %s" %
          (first_device, first_vidpid, vendor, product))
    print("WARNING: Experimental STM32F401 image vs documented GD32F303 MCU; no stock firmware backup exists; recovery may require SWD.")
    phrase = ("I ACCEPT BRICKING RISK; GD32F303 VS STM32F401; FLASH %s VID:PID %s PRODUCT %s; %s; RECOVERY MAY REQUIRE SWD" %
              (first_device, first_vidpid, product,
               "WITH USER-SUPPLIED BACKUP AND RECOVERY" if args.backup_file else "WITHOUT STOCK BACKUP"))
    if not args.yes:
        if args.non_interactive:
            raise ValueError("--non-interactive flash requires --yes --i-understand-the-risks")
        if input("Type exactly '%s' to authorize both firmware writes: " % phrase).strip() != phrase:
            raise ValueError("confirmation did not match")

    backups = [args.backup_file, args.recovery_file]
    if bool(backups[0]) != bool(backups[1]):
        raise ValueError("--backup-file and --recovery-file must be supplied together")
    common = ["--device", first_device, "--execute", "--i-understand-the-risks", "--yes"]
    if backups[0]:
        common += ["--stock-backup", backups[0], "--recovery-image", backups[1]]
    else:
        common += ["--allow-no-backup"]

    def run_stage(stage_args):
        parsed = flash_tool.parse_args().parse_args(stage_args)
        flash_tool.run(parsed,
                       identity_reader=FLASH_IDENTITY_READER,
                       runner=FLASH_RUNNER,
                       output=print)

    require_idle(args.moonraker_url, args.force)
    run_stage(common + ["--install-katapult", "--deployer", str(outputs[0]), "--vid-pid", first_vidpid])
    second_device, _ = wait_for_device(KATAPULT_VID_PID, args.enumeration_timeout)
    print("Katapult re-enumerated at %s (%s)" % (second_device, KATAPULT_VID_PID))
    # Stage two's device may be a new by-id path; preserve the same one-confirmation authorization.
    stage2_common = ["--device", second_device, "--execute", "--i-understand-the-risks", "--yes"]
    if backups[0]:
        stage2_common += ["--stock-backup", backups[0], "--recovery-image", backups[1]]
    else:
        stage2_common += ["--allow-no-backup"]
    require_idle(args.moonraker_url, args.force)
    run_stage(stage2_common + ["--flash-klipper", "--firmware", str(outputs[1])])
    final_device, _ = wait_for_device(KLIPPER_VID_PID, args.enumeration_timeout)
    by_id_dir = Path(os.environ.get("CANVAS_SERIAL_BY_ID_DIR", "/dev/serial/by-id"))
    by_id = [p for p in by_id_dir.iterdir() if os.path.realpath(p) == os.path.realpath(final_device)] if by_id_dir.is_dir() else []
    if by_id:
        final_device = str(by_id[0])
    print("Klipper device enumerated at: %s" % final_device)
    return 0


def install(args) -> int:
    klipper = Path(args.klipper_dir or os.environ.get("KLIPPER_DIR", str(Path.home() / "klipper"))).expanduser().resolve()
    config_dir = Path(args.config_dir or os.environ.get("CONFIG_DIR", str(Path.home() / "printer_data/config"))).expanduser().resolve()
    printer_cfg = config_dir / "printer.cfg"
    moonraker_cfg = Path(args.moonraker_config or config_dir / "moonraker.conf").expanduser().resolve()
    if not (klipper / "klippy/extras").is_dir() or not printer_cfg.is_file() or not moonraker_cfg.is_file():
        raise ValueError("expected Klipper extras, printer.cfg and moonraker.conf; use --klipper-dir/--config-dir to override")
    require_idle(args.moonraker_url, args.force)
    extruders, sensors = detect_config(printer_cfg)
    if not extruders:
        raise ValueError("[extruder] was not found in printer.cfg or included files")
    serial = args.serial
    if not serial:
        candidates = serial_paths()
        if len(candidates) != 1:
            raise ValueError("expected one /dev/serial/by-id device; found %d (use --serial)" % len(candidates))
        serial = str(candidates[0])
    if not Path(serial).is_absolute() or "\n" in serial or "\r" in serial:
        raise ValueError("--serial must be an absolute single-line device path")
    if sensors:
        sensor = ask("Select toolhead sensor (%s): " % ", ".join(sensors),
                     non_interactive=args.non_interactive, value=args.toolhead_sensor)
        if sensor not in sensors:
            raise ValueError("toolhead sensor must be one of: " + ", ".join(sensors))
        sensor_pin = None
    else:
        sensor = args.toolhead_sensor or "canvas_toolhead"
        if args.non_interactive and not args.toolhead_sensor:
            raise ValueError("--non-interactive with no existing sensor requires --toolhead-sensor and --toolhead-pin")
        sensor_pin = ask("Pin for new [filament_switch_sensor %s]: " % sensor,
                         non_interactive=args.non_interactive, value=args.toolhead_pin)
        if not re.fullmatch(r"[!^~A-Za-z0-9_.:+-]+", sensor_pin):
            raise ValueError("toolhead pin contains unsupported characters")
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", sensor):
        raise ValueError("toolhead sensor name contains unsupported characters")
    method = ask("Separation method (cutter/tip_forming): ", non_interactive=args.non_interactive,
                 value=args.separation_method).lower()
    if method not in ("cutter", "tip_forming"):
        raise ValueError("separation method must be cutter or tip_forming")

    old_printer = printer_cfg.read_text(encoding="utf-8")
    new_printer = old_printer
    if not any(line.strip().lower() == INCLUDE_LINE.lower() for line in old_printer.splitlines()):
        new_printer = old_printer.rstrip() + "\n\n" + INCLUDE_LINE + "\n"
    old_moonraker = moonraker_cfg.read_text(encoding="utf-8")
    block = update_manager_section(ROOT)
    existing = section_block(old_moonraker, "update_manager canvas-klipper")
    new_moonraker = old_moonraker
    if existing is None:
        new_moonraker = old_moonraker.rstrip() + "\n\n" + block
    elif existing != block.strip():
        raise ValueError("conflicting [update_manager canvas-klipper] section in " + str(moonraker_cfg))

    # Fail on protected generated files before changing main configs or linking extras.
    canvas_dir = config_dir / "canvas"
    marker = canvas_dir / ".canvas-klipper-config.sha256"
    if marker.exists() and (not marker.is_file() or
                            not re.fullmatch(r"[0-9a-f]{64}", marker.read_text(encoding="ascii").strip())):
        raise ValueError("refusing to overwrite unrecognized installer state file: " + str(marker))
    if canvas_dir.exists():
        canvas_config = canvas_dir / "canvas.cfg"
        if canvas_config.exists() and (not canvas_config.is_file() or
                                       not canvas_config.read_text(encoding="utf-8").startswith(MANAGED_HEADER)):
            raise ValueError("Refusing to overwrite unmarked user file: " + str(canvas_config))

    if new_printer != old_printer:
        saved = backup_path(printer_cfg)
        print("Backup: " + str(saved))
    if new_moonraker != old_moonraker:
        saved = backup_path(moonraker_cfg)
        print("Backup: " + str(saved))
    subprocess.run(["bash", str(ROOT / "install.sh")], check=True,
                   env={**os.environ, "KLIPPER_DIR": str(klipper)})
    canvas_changed = copy_templates(config_dir, sensor, method, serial, sensor_pin)
    if new_printer != old_printer:
        printer_cfg.write_text(new_printer, encoding="utf-8")
    if new_moonraker != old_moonraker:
        moonraker_cfg.write_text(new_moonraker, encoding="utf-8")
    if not canvas_config_complete(printer_cfg):
        print("Canvas setup scaffold installed. Klipper restart deferred: add all measured drv8833 and lane pin settings, then rerun install.")
        return 0

    previous_digest = marker.read_text(encoding="ascii").strip() if marker.is_file() else ""
    current_digest = config_digest(config_dir, printer_cfg, moonraker_cfg)
    restart_needed = (new_printer != old_printer or new_moonraker != old_moonraker or
                      canvas_changed or previous_digest != current_digest)
    if restart_needed:
        require_idle(args.moonraker_url, args.force)
        subprocess.run(["sudo", "systemctl", "restart", args.klipper_service], check=True)
        if new_moonraker != old_moonraker or not previous_digest:
            subprocess.run(["sudo", "systemctl", "restart", args.moonraker_service], check=True)
        marker.write_text(current_digest + "\n", encoding="ascii")
    else:
        print("Configuration is already current; no service restart needed.")
    return 0


def uninstall(args) -> int:
    klipper = Path(args.klipper_dir or os.environ.get("KLIPPER_DIR", str(Path.home() / "klipper"))).expanduser().resolve()
    config_dir = Path(args.config_dir or os.environ.get("CONFIG_DIR", str(Path.home() / "printer_data/config"))).expanduser().resolve()
    printer_cfg = config_dir / "printer.cfg"
    moonraker_cfg = Path(args.moonraker_config or config_dir / "moonraker.conf").expanduser().resolve()
    if not printer_cfg.is_file():
        raise ValueError("printer.cfg not found: " + str(printer_cfg))
    require_idle(args.moonraker_url, args.force)

    old_printer = printer_cfg.read_text(encoding="utf-8")
    new_printer = normalize_include(old_printer)
    old_moonraker = moonraker_cfg.read_text(encoding="utf-8") if moonraker_cfg.is_file() else None
    new_moonraker = old_moonraker
    if old_moonraker is not None:
        pattern = re.compile(r"(?ms)^\[update_manager canvas-klipper\]\s*\n.*?(?=^\[|\Z)", re.I)
        match = pattern.search(old_moonraker)
        if match:
            if match.group(0).strip() != update_manager_section(ROOT).strip():
                raise ValueError("refusing to remove a modified or non-project Moonraker update_manager section")
            new_moonraker = (old_moonraker[:match.start()] + old_moonraker[match.end():]).rstrip() + "\n"

    if new_printer != old_printer:
        backup_path(printer_cfg)
    if new_moonraker != old_moonraker and old_moonraker is not None:
        backup_path(moonraker_cfg)
    if new_printer != old_printer:
        printer_cfg.write_text(new_printer.rstrip() + "\n", encoding="utf-8")
    if new_moonraker != old_moonraker and new_moonraker is not None:
        moonraker_cfg.write_text(new_moonraker, encoding="utf-8")

    for source in (ROOT / "canvas/*.py", ROOT / "klipper/klippy/extras/drv8833.py"):
        for file in glob.glob(str(source)):
            dest = klipper / "klippy/extras" / Path(file).name
            if dest.is_symlink() and os.path.realpath(dest) == os.path.realpath(file):
                saved = move_to_backup(dest)
                print("Preserved installed symlink as " + str(saved))
    canvas_dir = config_dir / "canvas"
    if canvas_dir.is_dir():
        saved = move_to_backup(canvas_dir)
        print("Preserved Canvas config directory as " + str(saved))
    print("Removed the include/update-manager entries after backups. User config files were preserved as .bak; no files were deleted.")
    return 0


def status(args) -> int:
    klipper = Path(args.klipper_dir or os.environ.get("KLIPPER_DIR", str(Path.home() / "klipper"))).expanduser()
    config_dir = Path(args.config_dir or os.environ.get("CONFIG_DIR", str(Path.home() / "printer_data/config"))).expanduser()
    print("Klipper extras: " + str(klipper / "klippy/extras"))
    for filename in ("canvas.py", "drv8833.py"):
        path = klipper / "klippy/extras" / filename
        print("%s: %s" % (filename, "linked" if path.is_symlink() else "missing/other"))
    print("Canvas config: " + str(config_dir / "canvas"))
    try:
        print("Moonraker print state: " + query_print_state(args.moonraker_url))
    except (OSError, ValueError, urllib.error.URLError, json.JSONDecodeError):
        print("Moonraker print state: unknown")
    for path in serial_paths():
        info = device_info(path)
        print("Serial: %s (%s; %s)" % (path, info["vid_pid"] or "unknown VID:PID", info["product"] or "unknown product"))
    return 0


def add_common(parser):
    parser.add_argument("--moonraker-url", default=os.environ.get("MOONRAKER_URL", "http://127.0.0.1:7125"))
    parser.add_argument("--force", action="store_true", help="allow unknown Moonraker state only; never overrides printing/paused")


def make_parser():
    parser = argparse.ArgumentParser(prog="canvas-klipper.sh", description="Install, inspect, or flash Elegoo CANVAS v1 support.")
    sub = parser.add_subparsers(dest="command")
    sub.add_parser("help", help="show this help")
    p = sub.add_parser("flash", help="build (if needed) and flash Katapult then Klipper")
    add_common(p)
    p.add_argument("--device")
    p.add_argument("--vid-pid")
    p.add_argument("--backup-file")
    p.add_argument("--recovery-file")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--yes", action="store_true")
    p.add_argument("--i-understand-the-risks", action="store_true")
    p.add_argument("--non-interactive", action="store_true")
    p.add_argument("--enumeration-timeout", type=float, default=30)
    p = sub.add_parser("install", help="install extras and configure Canvas Klipper files")
    add_common(p)
    p.add_argument("--klipper-dir")
    p.add_argument("--config-dir")
    p.add_argument("--moonraker-config")
    p.add_argument("--serial")
    p.add_argument("--toolhead-sensor")
    p.add_argument("--toolhead-pin")
    p.add_argument("--separation-method", choices=("cutter", "tip_forming"))
    p.add_argument("--non-interactive", action="store_true")
    p.add_argument("--klipper-service", default="klipper")
    p.add_argument("--moonraker-service", default="moonraker")
    p = sub.add_parser("uninstall", help="preserve installed files and remove Canvas references")
    add_common(p)
    p.add_argument("--klipper-dir")
    p.add_argument("--config-dir")
    p.add_argument("--moonraker-config")
    p = sub.add_parser("status", help="show installation and local printer status")
    add_common(p)
    p.add_argument("--klipper-dir")
    p.add_argument("--config-dir")
    return parser


def main(argv=None) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)
    if args.command in (None, "help"):
        parser.print_help()
        return 0
    try:
        return {"flash": flash, "install": install, "uninstall": uninstall, "status": status}[args.command](args)
    except (ValueError, OSError, subprocess.SubprocessError, urllib.error.URLError) as exc:
        print("error: " + str(exc), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
